from envs.Env import Env
import time
if __name__ == "__main__":
    e = Env()
    state, info = e.reset()
    print(state)
    print("------------------------------------------------------------------------------------------")
    time.sleep(1)
    state, reward, done, info = e.step([(0,0)])
    print(e.getPowerConsumption())
    print(state, reward)
    print("------------------------------------------------------------------------------------------")
    state, reward, done, info = e.step([(1,0)])
    print(state, reward)
    print(e.getPowerConsumption())    
    print("------------------------------------------------------------------------------------------")
    state, reward, done, info = e.step([(0,1),(1,1)])
    print(state, reward)
    print(e.getPowerConsumption())
    print("------------------------------------------------------------------------------------------")
    state, reward, done, info = e.step([(0,0),(1,1)])
    print(state, reward)
    print(e.getPowerConsumption())
    print("------------------------------------------------------------------------------------------")

    e.reset()
